function printResults(dataset)
%PRINTRESULTS prints out results as formatted tables
%   PRINTRESULTS(dataset) searches all the experiment 
%   directories and prints out the best results as 
%   formatted tables

expDirs = getExpDirs(dataset);
results = cellfun(@(x) getBestResult(x), expDirs, 'UniformOutput', false);                               
results = cell2mat(results);

% Print table of completed experiments
completedTable = struct2table(results);
completedTable(strcmp({results.bestEpoch}, 'NA'), :) = [];
fprintf('\nCOMPLETED EXPERIMENTS \n');
prettyPrintTable(completedTable);

% Print table of unfinished experiments
unfinishedTable = struct2table(results);
unfinishedTable(~strcmp({results.bestEpoch}, 'NA'), :) = [];
fprintf('\nUNFINISHED EXPERIMENTS \n');
prettyPrintTable(unfinishedTable);

%-------------------------------
function prettyPrintTable(table)
%-------------------------------

columnWidths = [25 10 13 13];
fprintf('%s %s %s %s \n', repmat('-', 1, columnWidths(1)), ...
                       repmat('-', 1, columnWidths(2)), ...
                       repmat('-', 1, columnWidths(3)), ...
                       repmat('-', 1, columnWidths(4)));
fprintf('%-25s %-3s %13s %13s \n', 'Name', ...
                             'Best Epoch', ...
                             'Val Accuracy', ...
                             'Test Accuracy');
fprintf('%s %s %s %s \n', repmat('-', 1, columnWidths(1)), ...
                       repmat('-', 1, columnWidths(2)), ...
                       repmat('-', 1, columnWidths(3)), ...
                       repmat('-', 1, columnWidths(4)));
rowfun(@(name, epoch, valAccuracy, testAccuracy) ...
                    fprintf('%-25s %-10s %-13s %-13s \n', ...
                    name{:}, ...
                    epoch{:}, ...
                    strcat(valAccuracy{:}, '%'), ...
                    strcat(testAccuracy{:}, '%')), ...
                    table);