function experimentScheduler
%EXPERIMENTSCHEDULER runs the given list of experiments

  modelPairs = {{'resnet50_ft-dag', 32}, ...
								{'resnet50_scratch-dag', 32}, ...
								{'senet50_ft-dag', 32}, ...
								{'senet50_scratch-dag', 32}, ...
								{'vgg-m-face-bn', 192}, ...
								{'vgg_face', 32}, ...
								{'vgg-vd-face', 32}, ...
								{'resnet50-face-bn', 32}, ...
	             } ;

  for ii = 1:numel(modelPairs)
    modelName = modelPairs{ii}{1} ;
    batchSize = modelPairs{ii}{2} ;
		fer_baselines('modelName', modelName, ...
                  'train.batchSize', batchSize, ...
                  'finetuneLR', true, ...
                  'dataAug', true) ;
	end
